### ISSUE TITLE
How you implement T-CE and R-CE on the SGL and LightGCN?

### ISSUE THREAD

**Issue by TianRui-Song717** [Polaris-JZ/DDRM#1]
Nice job! I have a question about the settings of your experiment! You have mentioned in the paper, that T-CE and R-CE are adopted to LightGCN, but T-CE and R-CE are originally applied on pointwise BCE loss.

My questions are:
(1) The result of the pure LightGCN in your paper is trained with BPR or BCE?
(2) The result of T-CE and R-CE is trained with BCE loss or BPR loss?

**Comment by Polaris-JZ** [comment]
Thanks for your question.
1) The result of LightGCN is trained with BPR loss.
2) The result of T-CE and R-CE is also trained with BPR loss.

**Comment by TianRui-Song717** [comment]
> Thanks for your question.
> 
> 1. The result of LightGCN is trained with BPR loss.
> 2. The result of T-CE and R-CE is also trained with BPR loss.

Thanks for your reply!
